### ISSUE TITLE
type error reported for mark-spans.xsl

### ISSUE THREAD

**Issue by djbpitt** [wendellpiez/Luminescent#4]
Er ... is this user error? My "calabash" alias points to calabash and runs correctly otherwise.

CL1416a:Luminescent djbpitt$ calabash -dtext/plain@sonnets/ozymandias.lmnl LMNL-xLMNL.xpl
ERROR: file:/Users/djbpitt/Luminescent/lib/up/mark-spans.xsl:55:11:err:XPTY0020:Required item type of the context item for the attribute axis is node(); supplied value has item type xs:string
ERROR: Required item type of the context item for the attribute axis is node(); supplied value has item type xs:string
ERROR:     cause: file:/Users/djbpitt/Luminescent/lib/up/mark-spans.xsl:55:11:err:XPTY0020:Required item type of the context item for the attribute axis is node(); supplied value has item type xs:string
ERROR: Pipeline failed: Required item type of the context item for the attribute axis is node(); supplied value has item type xs:string
ERROR: Underlying exception: Required item type of the context item for the attribute axis is node(); supplied value has item type xs:string

**Comment by wendellpiez** [comment]
Not user error. Luminescent code must be tightened in a couple of places to get through tighter type checking in recent Saxon releases. I have found and fixed a couple of these but this one is deep in the pipeline and will require more banging to duplicate and fix.

**Comment by djbpitt** [comment]
Thanks! I'll stand ready to test a fix whenever it's ready.

**Comment by djbpitt** [comment]
Working correctly now
